AURORA STAKING
https://www.aurora.me.uk/login.php

YOU TAKE OUT YOUR MAIN COINS FROM INDODAX TRANSFER TO UNION WALLET
AND THEN SEND TO THE WEBSITE CLICK STAKING THE REWARDS OR YOUR COINS NEVER ARRIVED BACK IN YOUR WALLET
AND THE GOOD THING ITS
MAINWEBSITE
https://www.aurorachain.io/
MAINCOIN BLOCKCHAIN
https://browser.aurorachain.io/#/?lang=en
MAIN WALLET ADRESS

AOAcc2b5e171b3b98cf6713d539720877b7b42d9aba DEVELOPER WALLET

YOU TAKE OUT FROM INDODAX SEND TO YOU UNION WALLET
COME FROM THSI ADRESS
YOU SEND TO STAKING GOING TO THIS ADRESS

SCAMMER ITS OWN DEVELOPER PEOPLE WHEN HAVE THESE COINS SELL IT FAST WE REPORT THEM
MINIMUM 100 PLACES...
